 # Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Scott Brandon Moltu Williams
title: Senior Software Engineer
email: scott.brandon.williams@gmail.com
# website: https://moltude.micro.blog/

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  moltude

# Additional icon links
additional_links:
- title: moltude.micro.blog
  icon: fas fa-globe
  url: https://moltude.micro.blog

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hi, my name is Scott and I am a Senior Software Engineer. I have experience making software. I have worked at a number of companies gaining teamwork and leadership skills.

  What am I after or passionate about? 

  I am most skilled in: <mark>AWS</mark> and <mark>RUNNING</mark>

content:
  - title: Projects
    layout: list
    content: 
      - layout: center
        title: Some Projects
        sub_title: Project

  - title: Experience 
    layout: list 
    content:
      - layout: left
        title: Digital Public Library of America
        link: https://dp.la
        link_text: dp.la
        sub_title: Senior Software Engineer
        caption: 2020 - Present
        description: | # this will include new lines to allow paragraphs
            - Terraform?
            - Wikimedia
            - Ingest?
            - Aviation?
            - Metadata Working Group? 

      - layout: left
        # title: Digital Public Library of America
        # link: https://dp.la
        # link_text: dp.la
        sub_title: Software Developer
        caption: 2016 - 2020
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Yale University Art Gallery
        link: https://artgallery.yale.edu/
        link_text: artgallery.yale.edu
        sub_title: Data & Database Administrator
        caption: 2013 - 2016
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. 

            Digging holes is hard and I play my part making sure the whole company stays connected. 

      - layout: left
        title: Penn Museum
        link: https://penn.museum
        link_text: penn.museum
        sub_title: Collections Database Administrator
        caption: 2009 - 2013
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. 

            Digging holes is hard and I play my part making sure the whole company stays connected. 

  - title: Education 
    layout: list
    content: 
      # - layout: left
        # title: George Washington University
        # caption: 2011
        # sub_title: Museum Collections Management and Care
        # description: |
        #   What is a museum collections management cert? 
      - layout: left
        title: Miami University
        caption: 2003 - 2007
        sub_title: |
          BA History, Minor in Computer Science
        # description: | 
        #   What did I do with my time in college? 

  # - title: Education 
  #   layout: text
  #   content: |
  #     ### George Washington University, Washington D.C — Museum Collections Management and Care, 2011
  #     <br>
  #     ### Miami University, Oxford, OH — Bachelor of Arts, History Major, Computer Science Minor, 2007

  - title: About Me
    layout: text
    content: | 
      #### My other interests and hobbies are:
      - Running
      - Ski touring
      - Backpacking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
